### ISSUE TITLE
[Feature]선거시스템2

### ISSUE THREAD

**Issue by Yeogiwon** [Project-Fall/Project_Politic#14]
### 📔 작업 설명 📔
선거시스템, 그 중에서도 선거기간에 대한 사이클을 구현할 예정입니다. 중간 중간 턴의 수는 바뀔 수 있지만 선거 간의 텀은 일정할 예정입니다.

### 📝 작업 리스트 📝
- [x] 선거 버튼 만들기(평소에는 비활성화(회색)으로 되어있다가 나중에 선거가 있으면 활성화(아무색이나) ) 나중에는 버튼UI를 새로 만들어 스위칭할 예정
- [x] 26년 6월에 국회의원 선거가 활성화되도록, 지방선거와 동일하게 5월에 후보자 등록과 선거운동, 6월에 선거 진행하도록
- [x] 선거에 총선과 지방선거로 분류하기 
- [x] NPC 3개를 만들어 선거 시 랜덤으로 고르기

**Comment by ch-0012** [comment]
11/23
2026년 6월에 선거 버튼이 활성화되도록 만들어뒀습니다!
5월에 후보자 등록은 이후에 추가하겠습니당
